import './styles/main.scss';
import '@fortawesome/fontawesome-free/js/all.js';
// import './assets/imgs/holder.png';
// import './assets/imgs/london.jpg';
// import './assets/imgs/beach.jpg';
// import './assets/imgs/birdseyeview_ocean.jpg';
// import './assets/imgs/ocean-waves-beach-sunset.jpg';
// import './assets/imgs/palms.jpg';
// import './assets/imgs/palmsPink.jpg';
// import './assets/imgs/vacation1.jpg';
import './js/app.js';
